name: Readme update

on:
  workflow_run:
    workflows: ["Badges"]
    types:
      - completed
  workflow_dispatch:

jobs:
  readme-update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: main
        token: ${{ secrets.PAT }}

    - name: Build README.md from external markdown files
      run: |
        cat conf/github/header.md conf/github/badges.md conf/github/access.md conf/github/contribute.md conf/github/credits.md conf/github/testing.md conf/github/roadmap.md conf/github/footer.md > README.md

    - name: Add updated README.md to repository
      run: |
        git add README.md
        git commit -m "README.md updated." 
        git pull --rebase origin main
        git push origin main
